M48
; DRILL file {KiCad 9.0.6} date 2025-11-08T11:21:51+1100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-08T11:21:51+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.050
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C1.150
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C1.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T7C1.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T8C3.250
%
G90
G05
T1
X222.808Y-89.107
X222.808Y-94.887
T2
X214.348Y-119.123
T3
X93.725Y-72.0
X179.4Y-110.5
T4
X93.45Y-96.975
T5
X221.798Y-119.123
T6
X93.725Y-92.0
X110.6Y-110.5
X226.409Y-70.669
T7
X93.45Y-116.975
T8
X130.585Y-138.625
X142.015Y-138.625
M30
